"""Club van 20: de administratie (leden, betalingen per seizoen, projecten)
en alles wat daaruit volgt voor het kantine scherm en de publieke pagina.

Los van routes/club_van_20.py (de beheerpagina's) en routes/kiosk/ (het
kantine scherm), zodat allebei dezelfde regels gebruiken voor "wie staat er
op het scherm", "hoeveel is er opgehaald" en "wat is het volgende doel".

Een seizoen loopt van 1 juli t/m 30 juni, net als het voetbalseizoen, en
wordt opgeslagen als "2026-2027". Geen bijdrage-rij voor een lid in een
seizoen betekent simpelweg "niet gevraagd" -- een nieuw seizoen hoeft dus
nergens "gestart" te worden, het staat vanzelf klaar zodra 1 juli voorbij is.

Vroeger 1 bestand van ruim 1200 regels; nu opgesplitst per onderwerp
(seizoenen, administratie, scherm, importeren). Alles wordt hier opnieuw
beschikbaar gemaakt, dus `from club_van_20 import ...` werkt ongewijzigd.
"""

from club_van_20.seizoenen import (
    SEIZOEN_PATROON,
    SEIZOEN_STARTMAAND,
    alle_seizoenen,
    huidig_seizoen,
    normaliseer_seizoen,
    seizoen_kort,
    seizoen_van_datum,
    verschuif_seizoen,
)
from club_van_20.administratie import (
    BETAALWIJZEN,
    BIJDRAGE_STATUSSEN,
    BIJDRAGE_STATUS_LABELS,
    PROJECT_STATUS_LABELS,
    bereken_club_van_20_status,
    bijdrage_status,
    euro,
    financien,
    is_nieuw_lid,
    leden_met_bijdragen,
    project_kosten,
    seizoen_totalen,
    sla_bijdrage_op,
)
from club_van_20.scherm import (
    AFTEL_FORMAAT,
    AMSTERDAM,
    DAGNAMEN,
    MAANDNAMEN,
    STANDAARD_GLANS_VANAF_STERREN,
    STANDAARD_SEIZOENEN_PER_STER,
    _aankondiging_voor_dia,
    _ruimste_bereik,
    aankondiging,
    aftelmoment,
    bouw_slides,
    is_zichtbaar,
    nieuwe_leden,
    onbetaalde_leden,
    onbetaald_actie,
    raster_rijen,
    scherm_bereik,
    sterren_voor,
    team_stand,
    vakjes_breedte,
    verdeel_over_dias,
    verzoek_tekst,
    whatsapp_link,
    zichtbare_leden,
)
from club_van_20.importeren import (
    MAX_XLSX_XML_BYTES,
    _KOLOM_NAMEN,
    _STATUS_KOLOM,
    _STATUS_UIT_TEKST,
    _XLSX_NS,
    _bedrag,
    _bijdrage_ongewijzigd,
    _bijdrage_tekst,
    _lees_csv,
    _schoon,
    _xlsx_xml,
    import_rij_overzicht,
    import_samenvatting,
    parse_import,
    rijen_naar_csv,
    rijen_uit_xlsx,
    verlengingen_overzicht,
    voer_import_uit,
)

__all__ = [
    "SEIZOEN_PATROON",
    "SEIZOEN_STARTMAAND",
    "alle_seizoenen",
    "huidig_seizoen",
    "normaliseer_seizoen",
    "seizoen_kort",
    "seizoen_van_datum",
    "verschuif_seizoen",
    "BETAALWIJZEN",
    "BIJDRAGE_STATUSSEN",
    "BIJDRAGE_STATUS_LABELS",
    "PROJECT_STATUS_LABELS",
    "bereken_club_van_20_status",
    "bijdrage_status",
    "euro",
    "financien",
    "is_nieuw_lid",
    "leden_met_bijdragen",
    "project_kosten",
    "seizoen_totalen",
    "sla_bijdrage_op",
    "AFTEL_FORMAAT",
    "AMSTERDAM",
    "DAGNAMEN",
    "MAANDNAMEN",
    "STANDAARD_GLANS_VANAF_STERREN",
    "STANDAARD_SEIZOENEN_PER_STER",
    "_aankondiging_voor_dia",
    "_ruimste_bereik",
    "aankondiging",
    "aftelmoment",
    "bouw_slides",
    "is_zichtbaar",
    "nieuwe_leden",
    "onbetaalde_leden",
    "onbetaald_actie",
    "raster_rijen",
    "scherm_bereik",
    "sterren_voor",
    "team_stand",
    "vakjes_breedte",
    "verdeel_over_dias",
    "verzoek_tekst",
    "whatsapp_link",
    "zichtbare_leden",
    "MAX_XLSX_XML_BYTES",
    "_KOLOM_NAMEN",
    "_STATUS_KOLOM",
    "_STATUS_UIT_TEKST",
    "_XLSX_NS",
    "_bedrag",
    "_bijdrage_ongewijzigd",
    "_bijdrage_tekst",
    "_lees_csv",
    "_schoon",
    "_xlsx_xml",
    "import_rij_overzicht",
    "import_samenvatting",
    "parse_import",
    "rijen_naar_csv",
    "rijen_uit_xlsx",
    "verlengingen_overzicht",
    "voer_import_uit",
]
