"""Gedeelde hulpfuncties en -constantes voor de routes in routes/.

Mag zelf nooit iets uit app.py of routes/ importeren -- alleen andersom --
zodat er geen cirkelvuil kan ontstaan (zelfde patroon als database.py).

Vroeger 1 bestand van ruim 1500 regels; nu opgesplitst per onderwerp. Alles
wordt hier opnieuw beschikbaar gemaakt, dus `from helpers import ...` werkt
ongewijzigd."""

from helpers.basis import BASE_DIR
from helpers.afbeeldingen import (
    AFBEELDING_MAX_AFMETING,
    CLUB_LOGO_MAP,
    KIOSK_AFBEELDINGEN_MAP,
    PRODUCT_AFBEELDINGEN_MAP,
    STEM_AFBEELDINGEN_MAP,
    TOEGESTANE_AFBEELDING_EXTENSIES,
    _verkleind,
    bewaar_bier,
    bewaar_club_logo,
    sla_afbeelding_op,
    sla_club_logo_op,
    sla_stemoptie_afbeelding_op,
)
from helpers.kiosk_constanten import (
    HEX_KLEUR_PATROON,
    KIOSK_ELEMENT_TYPES,
    KIOSK_OVERGANGEN,
    KIOSK_OVERGANG_SLEUTELS,
    KIOSK_SPONSOR_SJABLONEN,
    KIOSK_SPONSOR_SJABLOON_AANGEPAST,
    KIOSK_SPONSOR_SJABLOON_SLEUTELS,
    KIOSK_SPONSOR_SJABLOON_VOORBEELDEN,
    KIOSK_TEKST_GROOTTES,
    KIOSK_TEKST_GROOTTE_SLEUTELS,
    KIOSK_TIJD_PATROON,
    KIOSK_UITLIJNINGEN,
    KIOSK_UITLIJNING_CSS,
    css_uitlijning,
)
from helpers.tijd import (
    dagdeel_groet,
    format_datum,
    format_datum_kort,
    now_datetime_local,
    now_str,
    vandaag_amsterdam,
    voeg_maanden_toe,
)
from helpers.web import (
    WEERGAVE_TELEFOON_PATROON,
    bepaal_weergave_modus,
    csrf_token,
    csv_response,
    is_ajax_verzoek,
    veilig_redirect_pad,
)
from helpers.toegang import (
    SECTIES,
    SECTIE_LABELS,
    genereer_wachtwoord_token,
    heeft_sectie_toegang,
    secties_lijst,
    vind_gebruiker_bij_token,
)
from helpers.mededelingen import (
    TAG_PATROON,
    met_tags_filter,
    stuur_tag_notificaties,
    vind_getagde_gebruikers,
)
from helpers.producten import (
    bereken_bestellijst_meldingen,
    bereken_fust_verkopen,
    bereken_voorspelde_tekorten,
    bestel_suggesties,
    besteleenheid_factor,
    besteleenheid_naam,
    bewaar_subcategorie,
    categorienamen_zonder_verkoopprijsplicht,
    naar_besteleenheden,
    naar_voorraadeenheden,
    regels_per_bestelling,
    vervang_product_prijsopties,
    verwerk_auto_inactief,
)
from helpers.omzet import (
    TRAININGSDAG,
    _aantal_dagen_met_weekdag,
    bereken_omzet_trend_periode,
    bereken_trend,
    bereken_week_overzicht,
)
from helpers.wedstrijden import (
    MOTM_RESULTATEN,
    _MAAND_KORT,
    _MOTM_SCORE,
    _WEEKDAG_KORT,
    bepaal_tegenstander,
    bereken_komende_thuiswedstrijden,
    bereken_wedstrijd_geschiedenis,
    club_van_team_naam,
    motm_resultaat_klopt,
    motm_score_weergave,
)
from helpers.kas import (
    KASSA_COUPURES,
    bereken_kassa_coupure_bedrag,
    bereken_kassa_telling_status,
    bereken_kassa_verschil_trend,
    bereken_kassalade_stand,
    bereken_kluis_stand,
    bereken_kluis_verschil_trend,
    kassa_telling_is_zelf_goedgekeurd,
)
from helpers.status import (
    bereken_bestelling_status,
    bereken_frituurvet_status,
    bereken_laatste_telling_status,
    bereken_pda_start,
)
from helpers.stemmen import stemming_is_open, tel_stemmers

__all__ = [
    "BASE_DIR",
    "AFBEELDING_MAX_AFMETING",
    "CLUB_LOGO_MAP",
    "KIOSK_AFBEELDINGEN_MAP",
    "PRODUCT_AFBEELDINGEN_MAP",
    "STEM_AFBEELDINGEN_MAP",
    "TOEGESTANE_AFBEELDING_EXTENSIES",
    "_verkleind",
    "bewaar_bier",
    "bewaar_club_logo",
    "sla_afbeelding_op",
    "sla_club_logo_op",
    "sla_stemoptie_afbeelding_op",
    "HEX_KLEUR_PATROON",
    "KIOSK_ELEMENT_TYPES",
    "KIOSK_OVERGANGEN",
    "KIOSK_OVERGANG_SLEUTELS",
    "KIOSK_SPONSOR_SJABLONEN",
    "KIOSK_SPONSOR_SJABLOON_AANGEPAST",
    "KIOSK_SPONSOR_SJABLOON_SLEUTELS",
    "KIOSK_SPONSOR_SJABLOON_VOORBEELDEN",
    "KIOSK_TEKST_GROOTTES",
    "KIOSK_TEKST_GROOTTE_SLEUTELS",
    "KIOSK_TIJD_PATROON",
    "KIOSK_UITLIJNINGEN",
    "KIOSK_UITLIJNING_CSS",
    "css_uitlijning",
    "dagdeel_groet",
    "format_datum",
    "format_datum_kort",
    "now_datetime_local",
    "now_str",
    "vandaag_amsterdam",
    "voeg_maanden_toe",
    "WEERGAVE_TELEFOON_PATROON",
    "bepaal_weergave_modus",
    "csrf_token",
    "csv_response",
    "is_ajax_verzoek",
    "veilig_redirect_pad",
    "SECTIES",
    "SECTIE_LABELS",
    "genereer_wachtwoord_token",
    "heeft_sectie_toegang",
    "secties_lijst",
    "vind_gebruiker_bij_token",
    "TAG_PATROON",
    "met_tags_filter",
    "stuur_tag_notificaties",
    "vind_getagde_gebruikers",
    "bereken_bestellijst_meldingen",
    "bereken_fust_verkopen",
    "bereken_voorspelde_tekorten",
    "bestel_suggesties",
    "besteleenheid_factor",
    "besteleenheid_naam",
    "bewaar_subcategorie",
    "categorienamen_zonder_verkoopprijsplicht",
    "naar_besteleenheden",
    "naar_voorraadeenheden",
    "regels_per_bestelling",
    "vervang_product_prijsopties",
    "verwerk_auto_inactief",
    "TRAININGSDAG",
    "_aantal_dagen_met_weekdag",
    "bereken_omzet_trend_periode",
    "bereken_trend",
    "bereken_week_overzicht",
    "MOTM_RESULTATEN",
    "_MAAND_KORT",
    "_MOTM_SCORE",
    "_WEEKDAG_KORT",
    "bepaal_tegenstander",
    "bereken_komende_thuiswedstrijden",
    "bereken_wedstrijd_geschiedenis",
    "club_van_team_naam",
    "motm_resultaat_klopt",
    "motm_score_weergave",
    "KASSA_COUPURES",
    "bereken_kassa_coupure_bedrag",
    "bereken_kassa_telling_status",
    "bereken_kassa_verschil_trend",
    "bereken_kassalade_stand",
    "bereken_kluis_stand",
    "bereken_kluis_verschil_trend",
    "kassa_telling_is_zelf_goedgekeurd",
    "bereken_bestelling_status",
    "bereken_frituurvet_status",
    "bereken_laatste_telling_status",
    "bereken_pda_start",
    "stemming_is_open",
    "tel_stemmers",
]
